defmodule FootballMarket.MixProject do
  use Mix.Project

  @cp1_coverage_inventory Code.eval_file(Path.join(__DIR__, "config/cp1_coverage_inventory.exs"))
                          |> elem(0)

  def project do
    [
      app: :football_market,
      version: "0.1.0",
      elixir: "~> 1.20.3",
      test_coverage: test_coverage(),
      test_ignore_filters: [
        "test/provider_contract_offline.exs",
        "test/fixtures/providers/cases.exs",
        "test/fixtures/providers/expected.exs",
        "test/fixtures/providers/source_a.exs",
        "test/fixtures/providers/source_b.exs"
      ],
      elixirc_paths: elixirc_paths(Mix.env()),
      start_permanent: Mix.env() == :prod,
      aliases: aliases(),
      deps: deps(),
      compilers: [:phoenix_live_view] ++ Mix.compilers(),
      listeners: [Phoenix.CodeReloader]
    ]
  end

  # Configuration for the OTP application.
  #
  # Type `mix help compile.app` for more information.
  def application do
    [
      mod: {FootballMarket.Application, []},
      extra_applications: [:logger, :runtime_tools]
    ]
  end

  def cli do
    [
      preferred_envs: [
        precommit: :test,
        "test.unit": :test,
        "test.integration": :test,
        "test.cp1_coverage": :test
      ]
    ]
  end

  # Specifies which paths to compile per environment.
  defp elixirc_paths(:test), do: ["lib", "test/support"]
  defp elixirc_paths(_), do: ["lib"]

  defp test_coverage do
    included = MapSet.new(Enum.map(@cp1_coverage_inventory, & &1.module))

    # These modules are generated by a test-only router and Inspect derives;
    # they have no standalone source entry in the CP1 inventory.
    generated_modules = [
      FootballMarketWeb.APIAuthenticationProbe.Router.Helpers,
      Inspect.FootballMarket.Accounts.ApiKey,
      Inspect.FootballMarket.Accounts.PasswordCredential
    ]

    ignored_modules =
      ["lib/**/*.ex", "test/support/**/*.ex"]
      |> Enum.flat_map(&Path.wildcard/1)
      |> Enum.flat_map(&source_modules/1)
      |> Enum.reject(&MapSet.member?(included, &1))
      |> Enum.concat(generated_modules)

    [
      output: System.get_env("CP1_COVERAGE_OUTPUT", "cover/cp1/staging"),
      summary: [threshold: 0],
      ignore_modules: ignored_modules
    ]
  end

  defp source_modules(path) do
    Regex.scan(~r/^defmodule\s+([A-Za-z0-9_.]+)/m, File.read!(path), capture: :all_but_first)
    |> List.flatten()
    |> Enum.map(&Module.concat([&1]))
  end

  # Specifies your project dependencies.
  #
  # Type `mix help deps` for examples and options.
  defp deps do
    [
      {:phoenix, "~> 1.8.13"},
      {:phoenix_ecto, "~> 4.5"},
      {:ecto_sql, "~> 3.13"},
      {:postgrex, ">= 0.0.0"},
      {:argon2_elixir, "4.1.3"},
      {:joken, "~> 2.7"},
      {:redix, "~> 1.5.2"},
      {:phoenix_html, "~> 4.1"},
      {:phoenix_live_reload, "~> 1.2", only: :dev},
      {:phoenix_live_view, "~> 1.2.0"},
      {:lazy_html, ">= 0.1.0", only: :test},
      {:esbuild, "~> 0.10", runtime: Mix.env() == :dev},
      {:tailwind, "~> 0.5", runtime: Mix.env() == :dev},
      {:heroicons,
       github: "tailwindlabs/heroicons",
       tag: "v2.2.0",
       sparse: "optimized",
       app: false,
       compile: false,
       depth: 1},
      {:daisyui,
       github: "saadeghi/daisyui",
       tag: "v5.5.20",
       sparse: "packages/bundle",
       app: false,
       compile: false,
       depth: 1},
      {:telemetry_metrics, "~> 1.0"},
      {:telemetry_poller, "~> 1.0"},
      {:gettext, "~> 1.0"},
      {:jason, "~> 1.2"},
      {:dns_cluster, "~> 0.2.0"},
      {:bandit, "~> 1.5"}
    ]
  end

  # Aliases are shortcuts or tasks specific to the current project.
  # For example, to install project dependencies and perform other setup tasks, run:
  #
  #     $ mix setup
  #
  # See the documentation for `Mix` for more info on aliases.
  defp aliases do
    [
      setup: ["deps.get", "infrastructure.database.setup", "assets.setup", "assets.build"],
      "ecto.create": ["infrastructure.database.create"],
      "ecto.migrate": ["infrastructure.database.migrate"],
      "ecto.setup": ["infrastructure.database.setup"],
      "test.prepare": ["infrastructure.database.test_prepare"],
      test: ["infrastructure.database.test_prepare", "test"],
      "assets.setup": ["tailwind.install --if-missing", "esbuild.install --if-missing"],
      "assets.build": ["compile", "tailwind football_market", "esbuild football_market"],
      "assets.deploy": [
        "tailwind football_market --minify",
        "esbuild football_market --minify",
        "phx.digest"
      ],
      precommit: ["compile --warnings-as-errors", "deps.unlock --unused", "format", "test"],
      "test.unit": [
        "run -e '{output, status} = System.cmd(\"sh\", [\"scripts/test_profile.sh\", \"unit\"], stderr_to_stdout: true); IO.write(output); System.halt(status)'"
      ],
      "test.integration": [
        "run -e '{output, status} = System.cmd(\"sh\", [\"scripts/test_profile.sh\", \"integration\"], stderr_to_stdout: true); IO.write(output); System.halt(status)'"
      ],
      "test.cp1_coverage": [
        "run -e '{output, status} = System.cmd(\"sh\", [\"scripts/coverage_report.sh\"], stderr_to_stdout: true); IO.write(output); System.halt(status)'"
      ]
    ]
  end
end
