sonar.organization=correasebastianemanuel
sonar.projectKey=CorreaSebastianEmanuel_desapp-grupo-m-2026s2
sonar.projectName=desapp-grupo-m-2026s2
sonar.sourceEncoding=UTF-8
sonar.sources=lib,assets/js
sonar.tests=test
sonar.exclusions=_build/**,deps/**,assets/vendor/**,priv/static/assets/**,priv/static/**/*-*.js,priv/static/**/*.map
